### ISSUE TITLE
thttpd doesn't start

### ISSUE THREAD

**Issue by kaihendry** [kaihendry/NixOS-smokeping#3]
`exiting due to signal 15`

**Comment by kaihendry** [comment]
```
○ thttpd.service
     Loaded: loaded (/etc/systemd/system/thttpd.service; enabled; preset: enabled)
     Active: inactive (dead) since Tue 2023-01-24 07:29:11 UTC; 3min 47s ago
   Duration: 4min 26.373s
   Main PID: 11295 (code=exited, status=1/FAILURE)
        CPU: 662ms

Jan 24 07:29:11 vnixos systemd[1]: Stopping thttpd.service...
Jan 24 07:29:11 vnixos thttpd[11295]:   libhttpd - 96 strings allocated, 23200 bytes (241.667 bytes/str)
Jan 24 07:29:11 vnixos thttpd[11295]:   map cache - 9 allocated, 9 active (95793 bytes), 0 free; hash size: 1024; expire age: 937
Jan 24 07:29:11 vnixos thttpd[11295]:   fdwatch - 97 polls (0.363296/sec)
Jan 24 07:29:11 vnixos thttpd[11295]:   timers - 3 allocated, 3 active, 0 free
Jan 24 07:29:11 vnixos thttpd[11295]: exiting due to signal 15
Jan 24 07:29:11 vnixos systemd[1]: thttpd.service: Main process exited, code=exited, status=1/FAILURE
Jan 24 07:29:11 vnixos systemd[1]: thttpd.service: Failed with result 'exit-code'.
Jan 24 07:29:11 vnixos systemd[1]: Stopped thttpd.service.
Jan 24 07:29:11 vnixos systemd[1]: thttpd.service: Consumed 662ms CPU time, received 9.6K IP traffic, sent 109.0K IP traffic.
```

**Comment by kaihendry** [comment]
Perhaps something to do with the host binding?

**Comment by mrVanDalo** [comment]
What do the logs say? 

journalctl -u thttp -f -n 100

**Comment by kaihendry** [comment]
This issue is that it was having issues binding to the hard coded 192.168.1.40. Once I fixed https://github.com/kaihendry/NixOS-smokeping/issues/5 ... this issue was resolved!

**Comment by kaihendry** [comment]
Doesn't start on my rpi3:

https://gist.github.com/kaihendry/b89261beda23c1106490c6467e47fdd2

it's probably because smokeping failed:
https://gist.github.com/kaihendry/49ac67902b9aaa4af709fcb59dd20aaf


```
❯ ssh root@192.168.1.26 systemctl cat thttpd | grep smokeping
Requires=smokeping.service
Environment="PATH=/nix/store/hjala5j03vxhkj6rvgj8kdigm1yrw0p4-bash-5.1-p16/bin:/nix/store/g1b03dxw040agn6xl1adsv0i34qwkmzp-rrdtool-1.7.2/bin:/nix/store/1id5297bsyllf5n55sxzmf96ikf53c56-smokeping-2.6.11/bin:/nix/store/k2c4qcb10r7g6hl07lqwffm3lfb7mdpx-thttpd-2.29/bin:/nix/store/jfs31rly5jmqpgw4nzspvxdar07a2fww-coreutils-9.1/bin:/nix/store/xwc5jihgni80ayrjwwlamcqv9pms7w5d-findutils-4.9.0/bin:/nix/store/ccby5y5baqwpwxn0bb4nc9r7gij62ybm-gnugrep-3.7/bin:/nix/store/h8mk4d5f39hsawsph7irxxynxdr1mphz-gnused-4.8/bin:/nix/store/6y0fgjph41kpm8c4rs94k25acxjrldwv-systemd-251.7/bin:/nix/store/hjala5j03vxhkj6rvgj8kdigm1yrw0p4-bash-5.1-p16/sbin:/nix/store/g1b03dxw040agn6xl1adsv0i34qwkmzp-rrdtool-1.7.2/sbin:/nix/store/1id5297bsyllf5n55sxzmf96ikf53c56-smokeping-2.6.11/sbin:/nix/store/k2c4qcb10r7g6hl07lqwffm3lfb7mdpx-thttpd-2.29/sbin:/nix/store/jfs31rly5jmqpgw4nzspvxdar07a2fww-coreutils-9.1/sbin:/nix/store/xwc5jihgni80ayrjwwlamcqv9pms7w5d-findutils-4.9.0/sbin:/nix/store/ccby5y5baqwpwxn0bb4nc9r7gij62ybm-gnugrep-3.7/sbin:/nix/store/h8mk4d5f39hsawsph7irxxynxdr1mphz-gnused-4.8/sbin:/nix/store/6y0fgjph41kpm8c4rs94k25acxjrldwv-systemd-251.7/sbin"
ExecStart=/nix/store/k2c4qcb10r7g6hl07lqwffm3lfb7mdpx-thttpd-2.29/bin/thttpd -u smokeping -c "**.fcgi" -d /var/lib/smokeping -h 0.0.0.0 -p 8081 -D -nos
```

**Comment by mrVanDalo** [comment]
It looks like systemd is killing thttpd, and yes it seems `thttpd` `Requires` `smokeping`.

But why smokeping is not runnig I don't know. It looks like there are syntax errors in `smokeping` 
```
Jan 27 14:08:07 rpi3 smokeping-pre-start[589]: /nix/store/mx8dxnbbgw7zhg4fr0fkd8d1bg985qfg-smokeping-2.8.2/bin/smokeping: line 4: use: command not found
```
I guess `use` is an `import` keyword.

**Comment by mrVanDalo** [comment]
https://github.com/NixOS/nixpkgs/blob/master/nixos/tests/smokeping.nix < this is the integration test for the smokeping service in NixOS maybe that helps.

**Comment by mrVanDalo** [comment]
Why do you use this as smokeping package : 
```
(builtins.getFlake "github:nixos/nixpkgs/e779fb4a661168a24db731e2e4fcd1d26c96985e").legacyPackages.x86_64-linux.smokeping;
```

It maybe you are using the wrong architecture here, this is running on a Raspberry Pi, right?
Also why override the package in the first place?

**Comment by kaihendry** [comment]
Matthew overrode the package because it was crazy out of date. https://youtu.be/w5kiN0vO51g?t=5705

Can the architecture be parameterised so that it uses the local arch?

**Comment by mrVanDalo** [comment]
https://github.com/numtide/flake-utils/blob/master/default.nix#L14 < I don't know which one is for your raspberry pi maybe one of the armv7 linux (or the aarch64 ?) use it instead of `x86_64-linux` in the string.

**Comment by mrVanDalo** [comment]
Btw you can follow more than one channel, and don't have to use git commits in you `configuration.nix`

https://discourse.nixos.org/t/2-channels-in-1-system-is-it-possible/10679

In your case that would be 

```
nix-channel --add unstable https://nixos.org/channels/nixpkgs-unstable
```

and than 

```
{ config
, pkgs
, ...
}: 
let
  unstable = import <unstable> {};
in
{
  services.smokeping = {
    package = unstable.smokeping;
    enable = true;
    port = 8081;
    host = "0.0.0.0";
    targetConfig = builtins.readFile ./Targets;
  };
}
```

This way you avoid naming you system (everytime).

**Comment by MatthewCroughan** [comment]
I recommend not using channels at all, and avoiding them at all costs. Follow the advice on https://zero-to-nix.com/concepts/nix

Avoid `<>` as this is impure and reads from the $NIX_PATH which is something that **doesn't come from your nix code** and is therefore not reproducible.

As for your issue, just use my override but make the architecture come from your `pkgs` by using an expression like `${pkgs.hostPlatform.system}` which will resolve to `x86_64-linux` if `pkgs` has been imported on x86, or `aarch64-linux` if you imported `pkgs` for `arm64`

`(builtins.getFlake "github:nixos/nixpkgs/e779fb4a661168a24db731e2e4fcd1d26c96985e").legacyPackages.${pkgs.hostPlatform.system}.smokeping;`

If you need help setting your system up as a `flake.nix`, let me know.

**Comment by MatthewCroughan** [comment]
As well as avoiding the old CLI and channels, I also recommend against using libraries and abstractions like flake-utils before you understand the language, and how this all fits together.
