### ISSUE TITLE
rrd migration from rpi:  ERROR: reached EOF while loading header rrd->ds_def

### ISSUE THREAD

**Issue by kaihendry** [kaihendry/NixOS-smokeping#4]
Some architecture issue perhaps?

**Comment by kaihendry** [comment]
`boot.binfmt.emulatedSystems = [ "aarch64-linux" ];` doesn't help

**Comment by mrVanDalo** [comment]
> `boot.binfmt.emulatedSystems = [ "aarch64-linux" ];` doesn't help

binfmt is for machines that create images for other architectures than their own

**Comment by kaihendry** [comment]
oh ok, so I can't hope to read a arm binary from amd64

**Comment by mrVanDalo** [comment]
Hmm don't know what you try to achieve. Also I'm not really fit with cross compile or raspberry pi

**Comment by kaihendry** [comment]
Going to give up trying to keep my historical data. .rrd's binary format is a bit annoying!
