### ISSUE TITLE
Host IP is hard coded

### ISSUE THREAD

**Issue by kaihendry** [kaihendry/NixOS-smokeping#5]
https://github.com/kaihendry/NixOS-smokeping/blob/ae9c0787097f71d89e276a36f55e7cbb65c4be22/smokeping.nix#L10

Not sure how to avoid this.

**Comment by mrVanDalo** [comment]
Why not use a dns?

**Comment by mrVanDalo** [comment]
![image](https://user-images.githubusercontent.com/839693/214522131-94d17923-3c26-4b7c-9eb6-c283695920af.jpeg)

Just leave it out

**Comment by kaihendry** [comment]
Probably just want 0.0.0.0 as suggested by https://twitter.com/MatthewCroughan/status/1618157941747773440

**Comment by mrVanDalo** [comment]
A sorry leaving it out would set it to `localhost` you want to set to to `null`.
